repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-json
        exclude: ^data/
      - id: check-yaml
        exclude: ^data/
      - id: end-of-file-fixer
        exclude: ^data/
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^data/


  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: ^data/

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=120]
        exclude: ^data/

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort
        args: [--line-length=120]
