repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: check-json
  - id: pretty-format-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: mixed-line-ending

- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    args: [--line-length=120]

- repo: https://github.com/asottile/blacken-docs
  rev: v1.10.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.10b0]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args: [--max-line-length=120, '--ignore=E203,W503', '--per-file-ignores=__init__.py:F401,F403']

- repo: https://github.com/PyCQA/isort
  rev: 5.9.1
  hooks:
  - id: isort
    args: [--line-length=120]

- repo: https://github.com/bemeurer/beautysh
  rev: v6.1.0
  hooks:
  - id: beautysh

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.4
  hooks:
  - id: pyupgrade
    args: [--py36-plus]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    args: [--no-strict-optional, --ignore-missing-imports]
    additional_dependencies: [types-PyYAML]
